doctrine_migrations:
    all_or_nothing: true
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
    services:
        'Doctrine\Migrations\Version\MigrationFactory': 'App\Infrastructure\Migration\MigrationFactoryDecorator'